name: Build bpy for macOS Intel

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Blender Tag to build'
        required: true
        default: 'v4.3.2'
      python_version:
        description: 'Python version to use'
        required: true
        default: '3.11.9'
  
  workflow_call:
    inputs:
      tag:
        description: 'Blender Tag to build'
        required: true
        type: string
      python_version:
        description: 'Python version to use'
        required: true
        default: '3.10.11'
        type: string

jobs:
  build:
    runs-on: macos-13
    permissions:
      contents: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set environment variables
        id: set_env
        run: |
          TAG=${{ inputs.tag || github.event.inputs.tag }}
          PYTHON_VERSION=${{ inputs.python_version || github.event.inputs.python_version }}
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV
          

      # - name: Checkout Blender repository recursively
      #   uses: actions/checkout@v2
      #   with:
      #     repository: blender/blender
      #     ref: ${{ env.TAG}}
      #     submodules: 'recursive'
      #     path: blender 


      # - name: Set up Conda
      #   uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     auto-update-conda: true
      #     python-version: 3.10.13
      #     activate-environment: bpy-env
      #     channels: conda-forge
      #     miniconda-version: "latest" 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}


      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip requests urllib3 ndg-httpsclient pyopenssl pyasn1
          pip install -r ./requirements.txt

      - name: Update Python
        run: |
          pip install -U pip setuptools wheel


      # - name: Install Conda Dependencies
      #   run: |
      #     conda install -y setuptools -c conda-forge

      # - name: Add conda subdirectories to PATH
      #   run: |
      #     for dir in $(find /Users/runner/conda_pkgs_dir/ -mindepth 1 -type d); do
      #       echo "$dir" >> $GITHUB_PATH
      #     done


      - name: Install  dependencies
        run: |
          brew install cmake subversion
      
      - name: Build Blender
        run: |
          python -m src.buildbpy.main --tag ${{ env.TAG }} --install --publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
        
      - name: Install compatible numpy version
        run: |
          pip install "numpy<2.0"

      - name: Test bpy and numpy import
        run: |
          python -c '
          import sys, traceback
          try:
              import numpy
              import bpy
              print("Imported bpy:", bpy.app.version)
          except Exception:
              traceback.print_exc()
              sys.exit(1)
          '
