name: Build bpy for macOS Silicon

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Blender Tag to build'
        required: true
        default: 'v4.3.2'
      python_version:
        description: 'Python version to use'
        required: true
        default: '3.11.9'

  workflow_call:
    inputs:
      tag:
        description: 'Blender Tag to build'
        required: true
        type: string
      python_version:
        description: 'Python version to use'
        required: true
        default: '3.10.11'
        type: string

jobs:
  build:
    runs-on: macos-15
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set environment variables
        id: set_env
        run: |
          TAG=${{ inputs.tag || github.event.inputs.tag }}
          PYTHON_VERSION=${{ inputs.python_version || github.event.inputs.python_version }}
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r ./requirements.txt

      - name: Install specific CMake version and build deps
        run: |
          brew uninstall --ignore-dependencies cmake || true
          brew install cmake@3.27
          brew link cmake@3.27 --force
          brew install subversion ffmpeg openimageio openexr
          cmake --version

      - name: Build Blender and bpy wheel
        run: |
          python -m src.buildbpy.main --tag ${{ env.TAG }} --install --publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
